### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by riwin** [Shauren/InterruptAnnouncer#2]
Message: ...ptAnnouncer\libs\ChatThrottleLib\ChatThrottleLib.lua:216: hooksecurefunc(): SendAddonMessage is not a function
Time: Mon Sep  3 23:29:27 2018
Count: 1
Stack: ...ptAnnouncer\libs\ChatThrottleLib\ChatThrottleLib.lua:216: hooksecurefunc(): SendAddonMessage is not a function
[C]: in function `hooksecurefunc'
...ptAnnouncer\libs\ChatThrottleLib\ChatThrottleLib.lua:216: in function `Init'
...ptAnnouncer\libs\ChatThrottleLib\ChatThrottleLib.lua:512: in main chunk

Locals:

**Comment by Shauren** [comment]
Should be good on next version (pending upload on curse)
